name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: MunifTanjim/setup-neovim-action@v1
      - run: |
          nvim --version

      - name: Prepare
        run: ./setup_test.sh

      - name: Test
        run: ./test.sh
